name: Application CI/CD

on:
  push:
    branches: ["main", "staging", "feature/**"]

permissions: 
  id-token: write # permissions inside of AWS
  contents: read # permissions to checkout the repo

jobs:
  app-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
        role-session-name: "test-app-deploy-session"
        aws-region: "us-east-1"

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: build backend image
      run: docker build -t backend:0.1 .
      working-directory: api-backend/

    - name: push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: backend
        IMAGE_TAG: 0.1
      run: |
        docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: log in to eks cluster
      run: aws eks update-kubeconfig --name dev_cluster
      
    - name: deploy the app
      working-directory: api-backend/
      run: kubectl apply -f k8s/backend-deployment.yaml

